[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/api/*"
  to = "http://Eventfinder-backend-env.eba-hsvjafpy.us-east-1.elasticbeanstalk.com/:splat"
  status = 200
  force = true

[build.environment]
  NODE_ENV = "production"
